language: node_js
sudo: false

os:
  - linux

node_js:
  - 8.9.0

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build && yarn run test

after_script:
  - yarn run coverage
